// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: RAD_Interface_V1.0

#ifndef _UI_COMP_MAINMENU_H
#define _UI_COMP_MAINMENU_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT MainMenu
#define UI_COMP_MAINMENU_MAINMENU 0
#define UI_COMP_MAINMENU_SIDEBAR 1
#define UI_COMP_MAINMENU_SIDEBAR_CHECKBOX 2
#define UI_COMP_MAINMENU_SIDEBAR_RETURN_HOME 3
#define UI_COMP_MAINMENU_SIDEBAR_ALARM_SETTING 4
#define UI_COMP_MAINMENU_SIDEBAR_DISPLAY_SETTING 5
#define UI_COMP_MAINMENU_SIDEBAR_DATETIME_SETTING 6
#define UI_COMP_MAINMENU_SIDEBAR_ABOUT_ 7
#define UI_COMP_MAINMENU_PANEL_HOME 8
#define UI_COMP_MAINMENU_PANEL_HOME_LABEL3 9
#define UI_COMP_MAINMENU_PANEL_ALARM_SET 10
#define UI_COMP_MAINMENU_PANEL_ALARM_SET_LABEL2 11
#define UI_COMP_MAINMENU_PANEL_DISPLAY_SET 12
#define UI_COMP_MAINMENU_PANEL_DISPLAY_SET_LABEL4 13
#define UI_COMP_MAINMENU_PANEL_DATETIME 14
#define UI_COMP_MAINMENU_PANEL_DATETIME_LABEL6 15
#define UI_COMP_MAINMENU_PANEL_ABOUT 16
#define UI_COMP_MAINMENU_PANEL_ABOUT_LABEL5 17
#define _UI_COMP_MAINMENU_NUM 18
lv_obj_t * ui_MainMenu_create(lv_obj_t * comp_parent);
void ui_event_comp_MainMenu_return_home(lv_event_t * e);
void ui_event_comp_MainMenu_alarm_setting(lv_event_t * e);
void ui_event_comp_MainMenu_display_setting(lv_event_t * e);
void ui_event_comp_MainMenu_datetime_setting(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
