// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: RAD_Interface_V1.0

#ifndef UI_MAIN_INTERFACE_H
#define UI_MAIN_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lv_port_indev.h"

// SCREEN: ui_Main_Interface
extern void ui_Main_Interface_screen_init(void);
extern void ui_Main_Interface_screen_destroy(void);
extern void ui_Main_Interface_screen_relocalize(void);
extern void ui_event_Main_Interface(lv_event_t * e);
extern lv_obj_t * ui_Main_Interface;
extern lv_obj_t * ui_Panel_temperature;
extern lv_obj_t * ui_temperature;
extern lv_obj_t * ui_data_temperature;
extern lv_obj_t * ui_Panel_humidity;
extern lv_obj_t * ui_humidity;
extern lv_obj_t * ui_data_humidity;
extern lv_obj_t * ui_Panel_baro;
extern lv_obj_t * ui_baro;
extern lv_obj_t * ui_data_baro;
extern lv_obj_t * ui_Panel_CO2;
extern lv_obj_t * ui_CO2;
extern lv_obj_t * ui_data_CO2;
extern lv_obj_t * ui_Panel_PM2_5;
extern lv_obj_t * ui_PM2_5;
extern lv_obj_t * ui_data_PM2_5;
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_alarm_on;
extern lv_obj_t * ui_alarm_off;
extern lv_obj_t * ui_led_on;
extern lv_obj_t * ui_led_off;
extern lv_obj_t * ui_Panel_doserate;
extern lv_obj_t * ui_radiation;
extern lv_obj_t * ui_data_doserate;
extern lv_obj_t * ui_data_unit;
extern lv_obj_t * ui_MainMenu1;
extern lv_obj_t * ui_sidebar;
extern void ui_event_alarm_setting(lv_event_t * e);
extern lv_obj_t * ui_alarm_setting;
extern void ui_event_display_setting(lv_event_t * e);
extern lv_obj_t * ui_display_setting;
extern void ui_event_datetime_setting(lv_event_t * e);
extern lv_obj_t * ui_datetime_setting;
extern void ui_event_about(lv_event_t * e);
extern lv_obj_t * ui_about;
extern lv_obj_t * ui_Panel_alarm_set;
extern lv_obj_t * ui_Label12;
extern void ui_event_alarm_light_sw(lv_event_t * e);
extern lv_obj_t * ui_alarm_light_sw;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_light_alarm_state;
extern void ui_event_alarm_beep_sw(lv_event_t * e);
extern lv_obj_t * ui_alarm_beep_sw;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_alarm_volume;
extern void ui_event_Hth_Set_Btn(lv_event_t * e);
extern lv_obj_t * ui_Hth_Set_Btn;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_high_threshold;
extern void ui_event_Lth_Set_Btn(lv_event_t * e);
extern lv_obj_t * ui_Lth_Set_Btn;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_low_threshold;
extern lv_obj_t * ui_Panel_volume_set;
extern lv_obj_t * ui_set_alarm_volume;
extern lv_obj_t * ui_Label8;
extern void ui_event_Slider_volume(lv_event_t * e);
extern lv_obj_t * ui_Slider_volume;
extern lv_obj_t * ui_Panel_high_th_set;
extern lv_obj_t * ui_Label2;
extern void ui_event_HthLeft3(lv_event_t * e);
extern lv_obj_t * ui_HthLeft3;
extern void ui_event_HthLeft2(lv_event_t * e);
extern lv_obj_t * ui_HthLeft2;
extern void ui_event_HthLeft1(lv_event_t * e);
extern lv_obj_t * ui_HthLeft1;
extern void ui_event_HthRight1(lv_event_t * e);
extern lv_obj_t * ui_HthRight1;
extern void ui_event_HthRight2(lv_event_t * e);
extern lv_obj_t * ui_HthRight2;
extern void ui_event_HthUnit(lv_event_t * e);
extern lv_obj_t * ui_HthUnit;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel_low_th_set;
extern lv_obj_t * ui_Label5;
extern void ui_event_LthLeft3(lv_event_t * e);
extern lv_obj_t * ui_LthLeft3;
extern void ui_event_LthLeft2(lv_event_t * e);
extern lv_obj_t * ui_LthLeft2;
extern void ui_event_LthLeft1(lv_event_t * e);
extern lv_obj_t * ui_LthLeft1;
extern void ui_event_LthRight1(lv_event_t * e);
extern lv_obj_t * ui_LthRight1;
extern void ui_event_LthRight2(lv_event_t * e);
extern lv_obj_t * ui_LthRight2;
extern void ui_event_LthUnit(lv_event_t * e);
extern lv_obj_t * ui_LthUnit;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel_display_set;
extern lv_obj_t * ui_Label7;
extern void ui_event_language_sw(lv_event_t * e);
extern lv_obj_t * ui_language_sw;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_sys_language;
extern void ui_event_screen_light_sw(lv_event_t * e);
extern lv_obj_t * ui_screen_light_sw;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_sys_bright;
extern lv_obj_t * ui_Panel_language_set;
extern lv_obj_t * ui_Label17;
extern void ui_event_LanguageChineseBtn(lv_event_t * e);
extern lv_obj_t * ui_LanguageChineseBtn;
extern lv_obj_t * ui_labelChinese;
extern void ui_event_LanguageEnglishBtn(lv_event_t * e);
extern lv_obj_t * ui_LanguageEnglishBtn;
extern lv_obj_t * ui_labelEnglish;
extern lv_obj_t * ui_Panel_bright_set;
extern lv_obj_t * ui_set_bright;
extern lv_obj_t * ui_Label10;
extern void ui_event_Slider_bright(lv_event_t * e);
extern lv_obj_t * ui_Slider_bright;
extern lv_obj_t * ui_Panel_datetime_set;
extern lv_obj_t * ui_Label14;
extern void ui_event_Year(lv_event_t * e);
extern lv_obj_t * ui_Year;
extern void ui_event_month(lv_event_t * e);
extern lv_obj_t * ui_month;
extern void ui_event_day(lv_event_t * e);
extern lv_obj_t * ui_day;
extern void ui_event_hour(lv_event_t * e);
extern lv_obj_t * ui_hour;
extern void ui_event_minute(lv_event_t * e);
extern lv_obj_t * ui_minute;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Panel_about;
extern lv_obj_t * ui_Label20;
extern void ui_event_SysAbout(lv_event_t * e);
extern lv_obj_t * ui_SysAbout;
extern lv_obj_t * ui_product_name;
extern lv_obj_t * ui_product_model;
extern lv_obj_t * ui_product_SN;
extern lv_obj_t * ui_software_version;
extern lv_obj_t * ui_contact_up;
extern lv_obj_t * ui_img_phone_number;
extern lv_obj_t * ui_phone_number;
extern lv_obj_t * ui_img_address;
extern lv_obj_t * ui_address;
extern lv_obj_t * ui_img_mailbox;
extern lv_obj_t * ui_mailbox;



// CUSTOM VARIABLES
extern lv_group_t *main_interface_g;
extern lv_group_t *menu_g;
extern lv_group_t *alarm_set_g;
extern lv_group_t *hth_set_g;
extern lv_group_t *lth_set_g;
extern lv_group_t *volume_set_g;
extern lv_group_t *display_set_g;
extern lv_group_t *bright_set_g;
extern lv_group_t *language_set_g;
extern lv_group_t *datetime_set_g;
extern lv_group_t *about_set_g;



#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

