// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: RAD_Interface_V1.0

#ifndef UI_START_INTERFACE_H
#define UI_START_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Start_interface
extern void ui_Start_interface_screen_init(void);
extern void ui_Start_interface_screen_destroy(void);
extern void ui_Start_interface_screen_relocalize(void);
extern lv_obj_t * ui_Start_interface;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

