// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: RAD_Interface_V1.0

#ifndef _RAD_INTERFACE_V1_0_UI_H
#define _RAD_INTERFACE_V1_0_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

//#include "lv_i18n.h"
#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "language.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Start_interface.h"
#include "screens/ui_Main_Interface.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * rotation_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * iconon_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * sidebaron_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * opaon_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * opaoff_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * choosenext_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * entryalarmsetting_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * choosefirst_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * chooseprev_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * chooselast_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_532493655);    // assets/温度正常.png
LV_IMG_DECLARE(ui_img_545021016);    // assets/湿度.png
LV_IMG_DECLARE(ui_img_1523901040);    // assets/大气压力.png
LV_IMG_DECLARE(ui_img_1464373361);    // assets/二氧化碳.png
LV_IMG_DECLARE(ui_img_pm2_5_png);    // assets/PM2.5.png
LV_IMG_DECLARE(ui_img_1985833602);    // assets/w0301010警铃.png
LV_IMG_DECLARE(ui_img_1779444627);    // assets/l-取消报警.png
LV_IMG_DECLARE(ui_img_602667123);    // assets/报警消息.png
LV_IMG_DECLARE(ui_img_834997458);    // assets/关闭报警备份 4.png
LV_IMG_DECLARE(ui_img_1957260177);    // assets/辐射.png
LV_IMG_DECLARE(ui_img_1777030953);    // assets/阈值设置.png
LV_IMG_DECLARE(ui_img_display_png);    // assets/Display.png
LV_IMG_DECLARE(ui_img_2138131786);    // assets/日历.png
LV_IMG_DECLARE(ui_img_182239421);    // assets/关于-版本.png
LV_IMG_DECLARE(ui_img_1640302447);    // assets/电话.png
LV_IMG_DECLARE(ui_img_820325126);    // assets/地址1.png
LV_IMG_DECLARE(ui_img_966723152);    // assets/邮箱.png

// FONTS
LV_FONT_DECLARE(ui_font_hansanbold128);
LV_FONT_DECLARE(ui_font_hansanbold24);
LV_FONT_DECLARE(ui_font_hansanbold28);
LV_FONT_DECLARE(ui_font_hansanbold32);
LV_FONT_DECLARE(ui_font_hansanbold36);
LV_FONT_DECLARE(ui_font_hansanbold48);
LV_FONT_DECLARE(ui_font_hansanbold64);

// UI INIT
void ui_init(void);
void ui_destroy(void);
void ui_relocalize(void);

// Language support
void update_all_ui_texts(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
