// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: RAD_Interface_V1.0

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void EntryAlarmSetOperation(lv_event_t * e);
void ReturnHomeOperation(lv_event_t * e);
void EntryDisplaySetOperation(lv_event_t * e);
void EntryDatetimeSetOperation(lv_event_t * e);
void EntryAboutOperation(lv_event_t * e);
void LightAlarmSwitchOperation(lv_event_t * e);
void ReturnMenuOperation(lv_event_t * e);
void AlarmLightSwFocusOperation(lv_event_t * e);
void AlarmLightSwDeFocusOperation(lv_event_t * e);
void AlarmBeepSwFocusOperation(lv_event_t * e);
void AlarmBeepSwDeFocusOperation(lv_event_t * e);
void HthSetBtnFocusOperation(lv_event_t * e);
void HthSetBtnDeFocusOperation(lv_event_t * e);
void LthSetBtnFocusOperation(lv_event_t * e);
void LthSetBtnDeFocusOperation(lv_event_t * e);
void ExitHthSetOperation(lv_event_t * e);
void ExitLthSetOperation(lv_event_t * e);
void ExitDisplaySetOperation(lv_event_t * e);
void LanguageSwFocusOperation(lv_event_t * e);
void LanguageSwDeFocusOperation(lv_event_t * e);
void ScreenLightSwFocusOperation(lv_event_t * e);
void ScreenLightSwDeFocusOperation(lv_event_t * e);
void ExitLanguageSetOperation(lv_event_t * e);
void LanguageChineseBtnFocusOperation(lv_event_t * e);
void LanguageChineseBtnDeFocusOperation(lv_event_t * e);
void LanguageEnglishBtnFocusOperation(lv_event_t * e);
void LanguageEnglishBtnDeFocusOperation(lv_event_t * e);
void ExitDatetimeSetOperation(lv_event_t * e);
void ExitAboutOperation(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
