// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: RAD_Interface_V1.0

#include "ui.h"
#include <stdlib.h>
#include <stdio.h>

#include "env_monitor.h"
#include "device_config.h"
#include "geiger.h"
#include "../../dev_protocol/net_raw/net_raw_app.h"
#include "language.h"


extern void Net_Config_Sync_To_Registers(Config_Index_t idx);
extern volatile Sys_Cfg_Struct sys_cfg;
extern Environment_Data_t env_data;
extern bool update_sys_cfg;

/* 辅助函数：更新声光报警状态和图标 */
static void Update_Alarm_Status_And_Icons(lv_obj_t * obj)
{
    bool th_zero = (sys_cfg.th_rh_rate == 0.0f && sys_cfg.th_rl_rate == 0.0f);
    bool volume_zero = (sys_cfg.alarm_volume == 0);
    
    /* 1. 更新声报警图标（与光报警一致，尊重 sys_cfg.alarm_sound） */
    if(th_zero || volume_zero || !sys_cfg.alarm_sound)
    {
        _ui_flag_modify(ui_alarm_on, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_alarm_off, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    else
    {
        _ui_flag_modify(ui_alarm_on, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_alarm_off, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    
    /* 2. 更新光报警图标和状态 */
    if(th_zero)
    {
        /* 阈值为 0，关闭光报警（即使音量不为 0） */
        _ui_flag_modify(ui_led_on, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_led_off, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        sys_cfg.alarm_light = 0;
    }
    else
    {
        /* 阈值不为 0，按照系统参数显示光报警状态 */
        if(sys_cfg.alarm_light)
        {
            _ui_flag_modify(ui_led_off, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
            _ui_flag_modify(ui_led_on, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        }
        else
        {
            _ui_flag_modify(ui_led_on, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
            _ui_flag_modify(ui_led_off, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        }
    }
    
    /* 3. 更新光报警状态文本（支持中英文，先同步 current_language 与 sys_cfg.language） */
    language_set_current((Language_t)sys_cfg.language);
    lv_label_set_text(ui_light_alarm_state, sys_cfg.alarm_light ? 
                      language_get_string(LANG_ALARM_STATE_ON) : 
                      language_get_string(LANG_ALARM_STATE_OFF));
    
    /* 4. 根据阈值是否为 0，修改光报警按钮和蜂鸣器音量按钮的文字颜色 */
    if(th_zero)
    {
        /* 阈值为 0，设置标签文字颜色为灰色 (RGB: 999999 = 0x999999) */
        lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_light_alarm_state, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_alarm_volume, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_group_remove_obj(ui_alarm_light_sw);
        lv_group_remove_obj(ui_alarm_beep_sw);
    }
    else
    {
        /* 阈值不为 0，恢复标签文字颜色为默认颜色（0xC6E1FF） */
        lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xC6E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0xC6E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_light_alarm_state, lv_color_hex(0xC6E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_alarm_volume, lv_color_hex(0xC6E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
        // lv_group_remove_all_objs(alarm_set_g);
        // lv_group_add_obj(alarm_set_g, ui_Hth_Set_Btn);
        // lv_group_add_obj(alarm_set_g, ui_Lth_Set_Btn);
        lv_group_add_obj(alarm_set_g, ui_alarm_light_sw);
        lv_group_add_obj(alarm_set_g, ui_alarm_beep_sw);
        // if(obj == ui_HthLeft3)
        //     lv_group_focus_obj(ui_Hth_Set_Btn);
        // else
        //     lv_group_focus_obj(ui_Lth_Set_Btn);
    }
    
    // printf("[报警同步] 阈值=%s, 音量=%d%%, 声报警=%d, 光报警=%d\r\n",
    //         th_zero ? "0" : "非 0", (int)sys_cfg.alarm_volume,
    //         (int)sys_cfg.alarm_sound, (int)sys_cfg.alarm_light);
}


void ReturnHomeOperation(lv_event_t * e)
{
	// Your code here
    _ui_flag_modify(ui_MainMenu1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    _ui_flag_modify(ui_Panel_alarm_set, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    _ui_flag_modify(ui_Panel_display_set, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    _ui_flag_modify(ui_Panel_datetime_set, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    _ui_flag_modify(ui_Panel_about, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    
    lv_indev_set_group(indev_keypad, main_interface_g);
    lv_group_focus_obj(ui_Main_Interface);
    lv_group_set_default(main_interface_g);
}

void EntryAlarmSetOperation(lv_event_t * e)
{
	// Your code here
    lv_indev_set_group(indev_keypad, alarm_set_g);
    lv_group_set_default(alarm_set_g);

    if(!sys_cfg.th_rh_rate && !sys_cfg.th_rl_rate)
    {
        lv_group_add_obj(alarm_set_g, ui_Hth_Set_Btn);
        lv_group_add_obj(alarm_set_g, ui_Lth_Set_Btn);
        lv_group_focus_obj(ui_Hth_Set_Btn);
    }
    else
    {
        lv_group_add_obj(alarm_set_g, ui_Hth_Set_Btn);
        lv_group_add_obj(alarm_set_g, ui_Lth_Set_Btn);
        lv_group_add_obj(alarm_set_g, ui_alarm_light_sw);
        lv_group_add_obj(alarm_set_g, ui_alarm_beep_sw);
        lv_group_focus_obj(ui_alarm_light_sw);
    }
}

void EntryDisplaySetOperation(lv_event_t * e)
{
	// Your code here
    lv_indev_set_group(indev_keypad, display_set_g);
    lv_group_add_obj(display_set_g, ui_language_sw);
    lv_group_add_obj(display_set_g, ui_screen_light_sw);
    lv_group_focus_obj(ui_language_sw);
    lv_group_set_default(display_set_g);
}

void EntryDatetimeSetOperation(lv_event_t * e)
{
	// Your code here
    lv_indev_set_group(indev_keypad, datetime_set_g);
    lv_group_add_obj(datetime_set_g, ui_Year);
    lv_group_add_obj(datetime_set_g, ui_month);
    lv_group_add_obj(datetime_set_g, ui_day);
    lv_group_add_obj(datetime_set_g, ui_hour);
    lv_group_add_obj(datetime_set_g, ui_minute);
    lv_group_focus_obj(ui_Year);
    lv_group_set_default(datetime_set_g);
}

void EntryAboutOperation(lv_event_t * e)
{
	// Your code here
    lv_obj_scroll_to(ui_SysAbout, 0, 0, LV_ANIM_OFF);
    lv_obj_set_style_text_color(ui_SysAbout, lv_color_hex(0x7EFEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_product_name, lv_color_hex(0x7EFEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_product_model, lv_color_hex(0x7EFEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_product_SN, lv_color_hex(0x7EFEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_software_version, lv_color_hex(0x7EFEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_contact_up, lv_color_hex(0x7EFEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_phone_number, lv_color_hex(0x7EFEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_address, lv_color_hex(0x7EFEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_mailbox, lv_color_hex(0x7EFEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    
    lv_indev_set_group(indev_keypad, about_set_g);
    lv_group_add_obj(about_set_g, ui_SysAbout);
    lv_group_focus_obj(ui_SysAbout);
    lv_group_set_default(about_set_g);
}

void LightAlarmSwitchOperation(lv_event_t * e)
{
	// Your code here
    const char *alarm_light_state;
    
    alarm_light_state = lv_label_get_text(ui_light_alarm_state);
    
    // 判断当前状态是开还是关（支持中英文）
    bool is_on = (strcmp(alarm_light_state, language_get_string(LANG_ALARM_STATE_ON)) == 0);
    
    if(is_on)
    {
        // 当前是开启状态，切换到关闭
        _ui_flag_modify(ui_led_on, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_led_off, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        lv_label_set_text(ui_light_alarm_state, language_get_string(LANG_ALARM_STATE_OFF));
        sys_cfg.alarm_light = 0;
    }
    else
    {
        /* 检查阈值是否都为 0，如果是则不允许开启光报警 */
        bool th_zero = (sys_cfg.th_rh_rate == 0.0f && sys_cfg.th_rl_rate == 0.0f);
        if(th_zero)
        {
            /* 阈值为 0，保持关闭状态 */
            _ui_flag_modify(ui_led_on, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
            _ui_flag_modify(ui_led_off, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
            lv_label_set_text(ui_light_alarm_state, language_get_string(LANG_ALARM_STATE_OFF));
            sys_cfg.alarm_light = 0;
            printf("[LVGL] 阈值为 0，无法开启光报警\r\n");
        }
        else
        {
            /* 阈值不为 0，允许开启 */
            _ui_flag_modify(ui_led_off, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
            _ui_flag_modify(ui_led_on, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
            lv_label_set_text(ui_light_alarm_state, language_get_string(LANG_ALARM_STATE_ON));
            sys_cfg.alarm_light = 1;
        }
    }
    
    if (DeviceConfig_WriteFromSysCfg() != 0)
        printf("[LVGL] 写入光报警开关到 flash %s 失败\r\n", DEVICE_CFG_STORAGE_LABEL);
    else
        printf("[LVGL] 已更新光报警开关：%d 并写入 flash %s\r\n", 
               (int)sys_cfg.alarm_light, DEVICE_CFG_STORAGE_LABEL);
    /* 同步到协议寄存器：仅更新控制位 */
    Net_Config_Sync_To_Registers(CFG_IDX_DEVICE_ADDR);
}

void ReturnMenuOperation(lv_event_t * e)
{
	// Your code here
    lv_group_t *def_g;

    def_g = lv_group_get_default();
    lv_group_remove_all_objs(def_g);
    lv_indev_set_group(indev_keypad, menu_g);
    lv_group_set_default(menu_g);
}

void ExitHthSetOperation(lv_event_t * e)
{
	// Your code here
    char change_val[16] = {0};
    char L3[2] = {0}, L2[2] = {0}, L1[2] = {0}, R1[2] = {0}, R2[2] = {0}, Unit[8] = {0};

    lv_roller_get_selected_str(ui_HthLeft3, L3, 2);
    lv_roller_get_selected_str(ui_HthLeft2, L2, 2);
    lv_roller_get_selected_str(ui_HthLeft1, L1, 2);
    lv_roller_get_selected_str(ui_HthRight1, R1, 2);
    lv_roller_get_selected_str(ui_HthRight2, R2, 2);
    lv_roller_get_selected_str(ui_HthUnit, Unit, sizeof(Unit));
    strcat(change_val, (L3[0] == '0') ? "" : L3);
    strcat(change_val, (L3[0] == '0') ? ((L2[0] == '0') ? "" : L2) : L2);
    strcat(change_val, L1);
    strcat(change_val, ".");
    strcat(change_val, R1);
    strcat(change_val, R2);
    lv_label_set_text_fmt(ui_high_threshold, "%s %s", change_val, Unit);
    
    // 解析并保存到 sys_cfg
    float hth_val = atof(change_val);
    if(!strcmp(Unit, "mSv/h"))
        sys_cfg.th_rh_rate = hth_val * 1000.0f;  // 转换为 uSv/h
    else
        sys_cfg.th_rh_rate = hth_val;
    
    // 判断阈值是否都为 0，如果是则关闭声光报警
    if(!sys_cfg.th_rh_rate && !sys_cfg.th_rl_rate)
    {
        sys_cfg.alarm_sound = 0;
        sys_cfg.alarm_light = 0;
    }
    
    // 写入 Flash
    if (DeviceConfig_WriteFromSysCfg() != 0)
        printf("[LVGL] 写入高位阈值到 flash %s 失败\r\n", DEVICE_CFG_STORAGE_LABEL);
    else
        printf("[LVGL] 已更新高位阈值：%.2f uSv/h 并写入 flash %s\r\n", 
                (double)sys_cfg.th_rh_rate, DEVICE_CFG_STORAGE_LABEL);
    
    /* 同步到协议寄存器：更新辐射剂量率阈值、报警使能、控制位 */
    Net_Config_Sync_To_Registers(CFG_IDX_RATE);
    Net_Config_Sync_To_Registers(CFG_IDX_ALARM_EN);
    Net_Config_Sync_To_Registers(CFG_IDX_DEVICE_ADDR);
    
    /* 更新 UI 界面的声光报警图标和状态 */
    Update_Alarm_Status_And_Icons(ui_HthLeft3);
    
    lv_indev_set_group(indev_keypad, alarm_set_g);
    lv_group_set_default(alarm_set_g);
    _ui_flag_modify(ui_Panel_high_th_set, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}

void ExitLthSetOperation(lv_event_t * e)
{
	// Your code here
    char change_val[16] = {0};
    char L3[2] = {0}, L2[2] = {0}, L1[2] = {0}, R1[2] = {0}, R2[2] = {0}, Unit[8] = {0};

    lv_roller_get_selected_str(ui_LthLeft3, L3, 2);
    lv_roller_get_selected_str(ui_LthLeft2, L2, 2);
    lv_roller_get_selected_str(ui_LthLeft1, L1, 2);
    lv_roller_get_selected_str(ui_LthRight1, R1, 2);
    lv_roller_get_selected_str(ui_LthRight2, R2, 2);
    lv_roller_get_selected_str(ui_LthUnit, Unit, sizeof(Unit));
    strcat(change_val, (L3[0] == '0') ? "" : L3);
    strcat(change_val, (L3[0] == '0') ? ((L2[0] == '0') ? "" : L2) : L2);
    strcat(change_val, L1);
    strcat(change_val, ".");
    strcat(change_val, R1);
    strcat(change_val, R2);
    lv_label_set_text_fmt(ui_low_threshold, "%s %s", change_val, Unit);
    
    // 解析并保存到 sys_cfg
    float lth_val = atof(change_val);
    if(!strcmp(Unit, "mSv/h"))
        sys_cfg.th_rl_rate = lth_val * 1000.0f;  // 转换为 uSv/h
    else
        sys_cfg.th_rl_rate = lth_val;
    
    // 判断阈值是否都为 0，如果是则关闭声光报警
    bool th_zero = (sys_cfg.th_rh_rate == 0.0f && sys_cfg.th_rl_rate == 0.0f);
    if(th_zero)
    {
        sys_cfg.alarm_sound = 0;
        sys_cfg.alarm_light = 0;
    }
    
    // 写入 Flash
    if (DeviceConfig_WriteFromSysCfg() != 0)
        printf("[LVGL] 写入低位阈值到 flash %s 失败\r\n", DEVICE_CFG_STORAGE_LABEL);
    else
        printf("[LVGL] 已更新低位阈值：%.2f uSv/h 并写入 flash %s\r\n", 
               (double)sys_cfg.th_rl_rate, DEVICE_CFG_STORAGE_LABEL);
    
    /* 同步到协议寄存器：更新辐射剂量率阈值、报警使能、控制位 */
    Net_Config_Sync_To_Registers(CFG_IDX_RATE);
    Net_Config_Sync_To_Registers(CFG_IDX_ALARM_EN);
    Net_Config_Sync_To_Registers(CFG_IDX_DEVICE_ADDR);
    
    /* 更新 UI 界面的声光报警图标和状态 */
    Update_Alarm_Status_And_Icons(ui_LthLeft3);

    lv_indev_set_group(indev_keypad, alarm_set_g);
    lv_group_set_default(alarm_set_g);
    _ui_flag_modify(ui_Panel_low_th_set, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}

void ExitDisplaySetOperation(lv_event_t * e)
{
	// Your code here
    lv_group_t *def_g;

    def_g = lv_group_get_default();
    lv_group_remove_all_objs(def_g);
    lv_indev_set_group(indev_keypad, menu_g);
    lv_group_set_default(menu_g);
}

void ExitLanguageSetOperation(lv_event_t * e)
{
	// Your code here
    _ui_flag_modify(ui_Panel_language_set, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    
    if(lv_group_get_focused(language_set_g) == ui_LanguageChineseBtn)
    {
        language_set_current(LANG_CHINESE);  // 先设置为中文
    }
    else
    {
        language_set_current(LANG_ENGLISH);  // 设置为英文
    }
    
    // 刷新所有 UI 文本（包括 ui_sys_language）
    language_refresh_ui_texts();
    
    // 保存语言设置到 Flash（可选）
    sys_cfg.language = language_get_current();
    update_sys_cfg = true;

    lv_indev_set_group(indev_keypad, display_set_g);
    lv_group_set_default(display_set_g);
}

void ExitDatetimeSetOperation(lv_event_t * e)
{
	// Your code here
    lv_group_t *def_g;
    char year[3] = {0}, month[3] = {0}, day[3] = {0}, hour[3] = {0}, minute[3] = {0};
    char datetime_buf[24];

    lv_roller_get_selected_str(ui_Year, year, 3);
    lv_roller_get_selected_str(ui_month, month, 3);
    lv_roller_get_selected_str(ui_day, day, 3);
    lv_roller_get_selected_str(ui_hour, hour, 3);
    lv_roller_get_selected_str(ui_minute, minute, 3);

    // 更新 env_data
    env_data.dt.year = atoi(year);  // 转换为完整年份（2000-2099）
    env_data.dt.month = atoi(month);
    env_data.dt.day = atoi(day);
    env_data.dt.hour = atoi(hour);
    env_data.dt.minute = atoi(minute);
    env_data.dt.second = 0;
    
    // 同步到 PCF8563
    pcf8563_set_cur_time(&env_data.dt);
    
    // 更新界面显示
    sprintf(datetime_buf, "20%02d/%02d/%02d  %02d:%02d", 
            env_data.dt.year, env_data.dt.month, env_data.dt.day,
            env_data.dt.hour, env_data.dt.minute);
    lv_label_set_text(ui_date, datetime_buf);
    
    // printf("[时间设置] 已更新：%s\r\n", datetime_buf);

    def_g = lv_group_get_default();
    lv_group_remove_all_objs(def_g);
    lv_indev_set_group(indev_keypad, menu_g);
    lv_group_set_default(menu_g);
}

void ExitAboutOperation(lv_event_t * e)
{
	// Your code here
    lv_group_t *def_g;
    
    lv_obj_scroll_to(ui_SysAbout, 0, 0, LV_ANIM_OFF);
    lv_obj_set_style_text_color(ui_SysAbout, lv_color_hex(0xC6E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_product_name, lv_color_hex(0xC6E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_product_model, lv_color_hex(0xC6E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_product_SN, lv_color_hex(0xC6E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_software_version, lv_color_hex(0xC6E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_contact_up, lv_color_hex(0xC6E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_phone_number, lv_color_hex(0xC6E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_address, lv_color_hex(0xC6E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_mailbox, lv_color_hex(0xC6E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    
    def_g = lv_group_get_default();
    lv_group_remove_all_objs(def_g);
    lv_indev_set_group(indev_keypad, menu_g);
    lv_group_set_default(menu_g);
}

void AlarmLightSwFocusOperation(lv_event_t * e)
{
	// Your code here
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x7EFEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_hansanbold36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_light_alarm_state, lv_color_hex(0x7EFEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_light_alarm_state, &ui_font_hansanbold36, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void AlarmLightSwDeFocusOperation(lv_event_t * e)
{
	// Your code here
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xC6E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_hansanbold28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_light_alarm_state, lv_color_hex(0xC6E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_light_alarm_state, &ui_font_hansanbold28, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void AlarmBeepSwFocusOperation(lv_event_t * e)
{
	// Your code here
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0x7EFEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &ui_font_hansanbold36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_alarm_volume, lv_color_hex(0x7EFEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_alarm_volume, &ui_font_hansanbold36, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void AlarmBeepSwDeFocusOperation(lv_event_t * e)
{
	// Your code here
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0xC6E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &ui_font_hansanbold28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_alarm_volume, lv_color_hex(0xC6E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_alarm_volume, &ui_font_hansanbold28, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void HthSetBtnFocusOperation(lv_event_t * e)
{
	// Your code here
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0x7EFEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &ui_font_hansanbold36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_high_threshold, lv_color_hex(0x7EFEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_high_threshold, &ui_font_hansanbold36, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void HthSetBtnDeFocusOperation(lv_event_t * e)
{
	// Your code here
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0xC6E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &ui_font_hansanbold28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_high_threshold, lv_color_hex(0xC6E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_high_threshold, &ui_font_hansanbold28, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void LthSetBtnFocusOperation(lv_event_t * e)
{
	// Your code here
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0x7EFEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &ui_font_hansanbold36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_low_threshold, lv_color_hex(0x7EFEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_low_threshold, &ui_font_hansanbold36, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void LthSetBtnDeFocusOperation(lv_event_t * e)
{
	// Your code here
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0xC6E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &ui_font_hansanbold28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_low_threshold, lv_color_hex(0xC6E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_low_threshold, &ui_font_hansanbold28, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void LanguageSwFocusOperation(lv_event_t * e)
{
	// Your code here
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0x7EFEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &ui_font_hansanbold36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_sys_language, lv_color_hex(0x7EFEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sys_language, &ui_font_hansanbold36, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void LanguageSwDeFocusOperation(lv_event_t * e)
{
	// Your code here
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xC6E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &ui_font_hansanbold28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_sys_language, lv_color_hex(0xC6E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sys_language, &ui_font_hansanbold28, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void ScreenLightSwFocusOperation(lv_event_t * e)
{
	// Your code here
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x7EFEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_hansanbold36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_sys_bright, lv_color_hex(0x7EFEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sys_bright, &ui_font_hansanbold36, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void ScreenLightSwDeFocusOperation(lv_event_t * e)
{
	// Your code here
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xC6E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_hansanbold28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_sys_bright, lv_color_hex(0xC6E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sys_bright, &ui_font_hansanbold28, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void LanguageChineseBtnFocusOperation(lv_event_t * e)
{
	// Your code here
    lv_obj_set_style_text_color(ui_labelChinese, lv_color_hex(0x7EFEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelChinese, &ui_font_hansanbold48, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void LanguageChineseBtnDeFocusOperation(lv_event_t * e)
{
	// Your code here
    lv_obj_set_style_text_color(ui_labelChinese, lv_color_hex(0xC6E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelChinese, &ui_font_hansanbold36, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void LanguageEnglishBtnFocusOperation(lv_event_t * e)
{
	// Your code here
    lv_obj_set_style_text_color(ui_labelEnglish, lv_color_hex(0x7EFEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelEnglish, &ui_font_hansanbold48, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void LanguageEnglishBtnDeFocusOperation(lv_event_t * e)
{
	// Your code here
	lv_obj_set_style_text_color(ui_labelEnglish, lv_color_hex(0xC6E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelEnglish, &ui_font_hansanbold36, LV_PART_MAIN | LV_STATE_DEFAULT);
}

