// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: RAD_Interface_V1.0

#ifndef UI_MAIN_INTERFACE_H
#define UI_MAIN_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main_Interface
extern void ui_Main_Interface_screen_init(void);
extern void ui_Main_Interface_screen_destroy(void);
extern void ui_Main_Interface_screen_relocalize(void);
extern void ui_event_Main_Interface(lv_event_t * e);
extern lv_obj_t * ui_Main_Interface;
extern lv_obj_t * ui_Panel_temperature;
extern lv_obj_t * ui_temperature;
extern lv_obj_t * ui_data_temperature;
extern lv_obj_t * ui_Panel_humidity;
extern lv_obj_t * ui_humidity;
extern lv_obj_t * ui_data_humidity;
extern lv_obj_t * ui_Panel_PM2_5;
extern lv_obj_t * ui_PM2_5;
extern lv_obj_t * ui_data_PM2_5;
extern lv_obj_t * ui_Panel_CO2;
extern lv_obj_t * ui_CO2;
extern lv_obj_t * ui_data_CO2;
extern lv_obj_t * ui_Panel_baro;
extern lv_obj_t * ui_baro;
extern lv_obj_t * ui_data_baro;
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_alarm_on;
extern lv_obj_t * ui_alarm_off;
extern lv_obj_t * ui_led_on;
extern lv_obj_t * ui_led_off;
extern lv_obj_t * ui_Panel_doserate;
extern lv_obj_t * ui_radiation;
extern lv_obj_t * ui_data_doserate;
extern lv_obj_t * ui_data_unit;
extern lv_obj_t * ui_MainMenu1;
extern lv_obj_t * ui_sidebar;
extern lv_obj_t * ui_choose_frame;
extern void ui_event_return_home(lv_event_t * e);
extern lv_obj_t * ui_return_home;
extern void ui_event_alarm_setting(lv_event_t * e);
extern lv_obj_t * ui_alarm_setting;
extern void ui_event_display_setting(lv_event_t * e);
extern lv_obj_t * ui_display_setting;
extern void ui_event_datetime_setting(lv_event_t * e);
extern lv_obj_t * ui_datetime_setting;
extern lv_obj_t * ui_about;
extern lv_obj_t * ui_Panel_alarm_set;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_cb_led_alarm;
extern lv_obj_t * ui_cb_beep_alarm;
extern lv_obj_t * ui_cb_high_th;
extern lv_obj_t * ui_cb_low_th;
extern void ui_event_mod_alarm_volume(lv_event_t * e);
extern lv_obj_t * ui_mod_alarm_volume;
extern void ui_event_mod_high_threshold(lv_event_t * e);
extern lv_obj_t * ui_mod_high_threshold;
extern void ui_event_mod_low_threshold(lv_event_t * e);
extern lv_obj_t * ui_mod_low_threshold;
extern lv_obj_t * ui_alarm_volume;
extern lv_obj_t * ui_high_threshold;
extern lv_obj_t * ui_low_threshold;
extern lv_obj_t * ui_Panel_high_th_set;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_HthLeft3;
extern lv_obj_t * ui_HthLeft2;
extern lv_obj_t * ui_HthLeft1;
extern lv_obj_t * ui_HthRight2;
extern lv_obj_t * ui_HthRight1;
extern lv_obj_t * ui_HthUnit;
extern void ui_event_Label1(lv_event_t * e);
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel_low_th_set;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_LthLeft3;
extern lv_obj_t * ui_LthLeft2;
extern lv_obj_t * ui_LthLeft1;
extern lv_obj_t * ui_LthRight1;
extern lv_obj_t * ui_LthRight2;
extern lv_obj_t * ui_LthUnit;
extern void ui_event_Label3(lv_event_t * e);
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel_volume_set;
extern void ui_event_set_alarm_volume(lv_event_t * e);
extern lv_obj_t * ui_set_alarm_volume;
extern lv_obj_t * ui_Label8;
extern void ui_event_Slider_volume(lv_event_t * e);
extern lv_obj_t * ui_Slider_volume;
extern lv_obj_t * ui_Panel_display_set;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_sys_language;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_sys_bright;
extern void ui_event_mod_language(lv_event_t * e);
extern lv_obj_t * ui_mod_language;
extern void ui_event_mod_bright(lv_event_t * e);
extern lv_obj_t * ui_mod_bright;
extern lv_obj_t * ui_Panel_bright_set;
extern void ui_event_set_bright(lv_event_t * e);
extern lv_obj_t * ui_set_bright;
extern lv_obj_t * ui_Label10;
extern void ui_event_Slider_bright(lv_event_t * e);
extern lv_obj_t * ui_Slider_bright;
extern lv_obj_t * ui_Panel_language_set;
extern lv_obj_t * ui_Label17;
extern void ui_event_HthLeft7(lv_event_t * e);
extern lv_obj_t * ui_HthLeft7;
extern lv_obj_t * ui_Panel_datetimr_set;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_HthLeft8;
extern lv_obj_t * ui_HthLeft4;
extern lv_obj_t * ui_HthLeft5;
extern lv_obj_t * ui_HthRight5;
extern lv_obj_t * ui_HthRight3;
extern void ui_event_Label4(lv_event_t * e);
extern lv_obj_t * ui_Label4;
extern void ui_event_Label13(lv_event_t * e);
extern lv_obj_t * ui_Label13;
extern void ui_event_Label15(lv_event_t * e);
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Panel_about;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_sys_about;
extern lv_obj_t * ui_product_name;
extern lv_obj_t * ui_product_model;
extern lv_obj_t * ui_product_SN;
extern lv_obj_t * ui_software_version;
extern lv_obj_t * ui_contact_up;
extern lv_obj_t * ui_img_phone_number;
extern lv_obj_t * ui_phone_number;
extern lv_obj_t * ui_img_address;
extern lv_obj_t * ui_address;
extern lv_obj_t * ui_img_mailbox;
extern lv_obj_t * ui_mailbox;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

