// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: RAD_Interface_V1.0

#include "../ui.h"

lv_obj_t * ui_Start_interface = NULL;
// event funtions

// build funtions

void ui_Start_interface_screen_init(void)
{
    ui_Start_interface = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Start_interface, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_Start_interface_screen_destroy(void)
{
    if(ui_Start_interface) lv_obj_del(ui_Start_interface);

    // NULL screen variables
    ui_Start_interface = NULL;

}

void ui_Start_interface_screen_relocalize(void)
{
    // label widgets on screen

}
