// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RAD_Interface_V1.0

#include "../ui.h"

void ui_event_comp_MainMenu_return_home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_MainMenu = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_flag_modify(comp_MainMenu[UI_COMP_MAINMENU_MAINMENU], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        // choosenext_Animation(comp_MainMenu[UI_COMP_MAINMENU_SIDEBAR_CHECKBOX], 0);
        _ui_flag_modify(comp_MainMenu[UI_COMP_MAINMENU_PANEL_HOME], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(comp_MainMenu[UI_COMP_MAINMENU_PANEL_ALARM_SET], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        opaon_Animation(comp_MainMenu[UI_COMP_MAINMENU_PANEL_ALARM_SET], 0);
    }
}

void ui_event_comp_MainMenu_alarm_setting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_MainMenu = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        // choosenext_Animation(comp_MainMenu[UI_COMP_MAINMENU_SIDEBAR_CHECKBOX], 0);
        _ui_flag_modify(comp_MainMenu[UI_COMP_MAINMENU_PANEL_ALARM_SET], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(comp_MainMenu[UI_COMP_MAINMENU_PANEL_DISPLAY_SET], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        opaon_Animation(comp_MainMenu[UI_COMP_MAINMENU_PANEL_DISPLAY_SET], 0);
    }
}

void ui_event_comp_MainMenu_display_setting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_MainMenu = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_flag_modify(comp_MainMenu[UI_COMP_MAINMENU_PANEL_DISPLAY_SET], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(comp_MainMenu[UI_COMP_MAINMENU_PANEL_DATETIME], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        // choosenext_Animation(comp_MainMenu[UI_COMP_MAINMENU_SIDEBAR_CHECKBOX], 0);
        opaon_Animation(comp_MainMenu[UI_COMP_MAINMENU_PANEL_DATETIME], 0);
    }
}

void ui_event_comp_MainMenu_datetime_setting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_MainMenu = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_flag_modify(comp_MainMenu[UI_COMP_MAINMENU_PANEL_DATETIME], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(comp_MainMenu[UI_COMP_MAINMENU_PANEL_ABOUT], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        // choosenext_Animation(comp_MainMenu[UI_COMP_MAINMENU_SIDEBAR_CHECKBOX], 0);
        opaon_Animation(comp_MainMenu[UI_COMP_MAINMENU_PANEL_ABOUT], 0);
    }
}

// COMPONENT MainMenu

lv_obj_t * ui_MainMenu_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_MainMenu;
    cui_MainMenu = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_MainMenu, 854);
    lv_obj_set_height(cui_MainMenu, 480);
    lv_obj_set_align(cui_MainMenu, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_MainMenu, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(cui_MainMenu, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_MainMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_MainMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_MainMenu, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_MainMenu, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_MainMenu, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_MainMenu, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_MainMenu, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_sidebar;
    cui_sidebar = lv_obj_create(cui_MainMenu);
    lv_obj_set_width(cui_sidebar, 80);
    lv_obj_set_height(cui_sidebar, 345);
    lv_obj_set_align(cui_sidebar, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(cui_sidebar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_sidebar, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_sidebar, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_sidebar, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_sidebar, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_sidebar, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_checkbox;
    cui_checkbox = lv_obj_create(cui_sidebar);
    lv_obj_set_width(cui_checkbox, 60);
    lv_obj_set_height(cui_checkbox, 60);
    lv_obj_set_align(cui_checkbox, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(cui_checkbox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_checkbox, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_checkbox, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_checkbox, lv_color_hex(0x7EFEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_checkbox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_checkbox, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_checkbox, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_return_home;
    cui_return_home = lv_img_create(cui_sidebar);
    lv_obj_set_width(cui_return_home, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_return_home, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_return_home, 0);
    lv_obj_set_y(cui_return_home, 15);
    lv_obj_set_align(cui_return_home, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(cui_return_home, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_return_home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_alarm_setting;
    cui_alarm_setting = lv_img_create(cui_sidebar);
    lv_img_set_src(cui_alarm_setting, &ui_img_1777030953);
    lv_obj_set_width(cui_alarm_setting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_alarm_setting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_alarm_setting, 0);
    lv_obj_set_y(cui_alarm_setting, 80);
    lv_obj_set_align(cui_alarm_setting, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(cui_alarm_setting, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_alarm_setting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_display_setting;
    cui_display_setting = lv_img_create(cui_sidebar);
    lv_img_set_src(cui_display_setting, &ui_img_display_png);
    lv_obj_set_width(cui_display_setting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_display_setting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_display_setting, 0);
    lv_obj_set_y(cui_display_setting, 145);
    lv_obj_set_align(cui_display_setting, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(cui_display_setting, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_display_setting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_datetime_setting;
    cui_datetime_setting = lv_img_create(cui_sidebar);
    lv_img_set_src(cui_datetime_setting, &ui_img_2138131786);
    lv_obj_set_width(cui_datetime_setting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_datetime_setting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_datetime_setting, 0);
    lv_obj_set_y(cui_datetime_setting, 210);
    lv_obj_set_align(cui_datetime_setting, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(cui_datetime_setting, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_datetime_setting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_about_;
    cui_about_ = lv_img_create(cui_sidebar);
    lv_img_set_src(cui_about_, &ui_img_182239421);
    lv_obj_set_width(cui_about_, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_about_, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_about_, 0);
    lv_obj_set_y(cui_about_, 275);
    lv_obj_set_align(cui_about_, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(cui_about_, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_about_, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Panel_home;
    cui_Panel_home = lv_obj_create(cui_MainMenu);
    lv_obj_set_height(cui_Panel_home, 60);
    lv_obj_set_width(cui_Panel_home, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(cui_Panel_home, -94);
    lv_obj_set_y(cui_Panel_home, -130);
    lv_obj_set_align(cui_Panel_home, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(cui_Panel_home, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(cui_Panel_home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Panel_home, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label3;
    cui_Label3 = lv_label_create(cui_Panel_home);
    lv_obj_set_width(cui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label3, "返回主页");
    lv_obj_set_style_text_color(cui_Label3, lv_color_hex(0xD2D2D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label3, &ui_font_hansanbold32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Panel_alarm_set;
    cui_Panel_alarm_set = lv_obj_create(cui_MainMenu);
    lv_obj_set_height(cui_Panel_alarm_set, 60);
    lv_obj_set_width(cui_Panel_alarm_set, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(cui_Panel_alarm_set, -94);
    lv_obj_set_y(cui_Panel_alarm_set, -65);
    lv_obj_set_align(cui_Panel_alarm_set, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(cui_Panel_alarm_set, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Panel_alarm_set, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label2;
    cui_Label2 = lv_label_create(cui_Panel_alarm_set);
    lv_obj_set_width(cui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label2, "报警设置");
    lv_obj_set_style_text_color(cui_Label2, lv_color_hex(0xD2D2D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label2, &ui_font_hansanbold32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Panel_display_set;
    cui_Panel_display_set = lv_obj_create(cui_MainMenu);
    lv_obj_set_height(cui_Panel_display_set, 60);
    lv_obj_set_width(cui_Panel_display_set, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(cui_Panel_display_set, -94);
    lv_obj_set_y(cui_Panel_display_set, 0);
    lv_obj_set_align(cui_Panel_display_set, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(cui_Panel_display_set, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(cui_Panel_display_set, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Panel_display_set, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label4;
    cui_Label4 = lv_label_create(cui_Panel_display_set);
    lv_obj_set_width(cui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label4, "显示设置");
    lv_obj_set_style_text_color(cui_Label4, lv_color_hex(0xD2D2D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label4, &ui_font_hansanbold32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Panel_datetime;
    cui_Panel_datetime = lv_obj_create(cui_MainMenu);
    lv_obj_set_height(cui_Panel_datetime, 60);
    lv_obj_set_width(cui_Panel_datetime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(cui_Panel_datetime, -94);
    lv_obj_set_y(cui_Panel_datetime, 65);
    lv_obj_set_align(cui_Panel_datetime, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(cui_Panel_datetime, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(cui_Panel_datetime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Panel_datetime, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label6;
    cui_Label6 = lv_label_create(cui_Panel_datetime);
    lv_obj_set_width(cui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label6, "时间设置");
    lv_obj_set_style_text_color(cui_Label6, lv_color_hex(0xD2D2D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label6, &ui_font_hansanbold32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Panel_about;
    cui_Panel_about = lv_obj_create(cui_MainMenu);
    lv_obj_set_height(cui_Panel_about, 60);
    lv_obj_set_width(cui_Panel_about, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(cui_Panel_about, -94);
    lv_obj_set_y(cui_Panel_about, 130);
    lv_obj_set_align(cui_Panel_about, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(cui_Panel_about, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(cui_Panel_about, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Panel_about, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label5;
    cui_Label5 = lv_label_create(cui_Panel_about);
    lv_obj_set_width(cui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label5, "关于本机");
    lv_obj_set_style_text_color(cui_Label5, lv_color_hex(0xD2D2D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label5, &ui_font_hansanbold32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_MAINMENU_NUM);
    children[UI_COMP_MAINMENU_MAINMENU] = cui_MainMenu;
    children[UI_COMP_MAINMENU_SIDEBAR] = cui_sidebar;
    children[UI_COMP_MAINMENU_SIDEBAR_CHECKBOX] = cui_checkbox;
    children[UI_COMP_MAINMENU_SIDEBAR_RETURN_HOME] = cui_return_home;
    children[UI_COMP_MAINMENU_SIDEBAR_ALARM_SETTING] = cui_alarm_setting;
    children[UI_COMP_MAINMENU_SIDEBAR_DISPLAY_SETTING] = cui_display_setting;
    children[UI_COMP_MAINMENU_SIDEBAR_DATETIME_SETTING] = cui_datetime_setting;
    children[UI_COMP_MAINMENU_SIDEBAR_ABOUT_] = cui_about_;
    children[UI_COMP_MAINMENU_PANEL_HOME] = cui_Panel_home;
    children[UI_COMP_MAINMENU_PANEL_HOME_LABEL3] = cui_Label3;
    children[UI_COMP_MAINMENU_PANEL_ALARM_SET] = cui_Panel_alarm_set;
    children[UI_COMP_MAINMENU_PANEL_ALARM_SET_LABEL2] = cui_Label2;
    children[UI_COMP_MAINMENU_PANEL_DISPLAY_SET] = cui_Panel_display_set;
    children[UI_COMP_MAINMENU_PANEL_DISPLAY_SET_LABEL4] = cui_Label4;
    children[UI_COMP_MAINMENU_PANEL_DATETIME] = cui_Panel_datetime;
    children[UI_COMP_MAINMENU_PANEL_DATETIME_LABEL6] = cui_Label6;
    children[UI_COMP_MAINMENU_PANEL_ABOUT] = cui_Panel_about;
    children[UI_COMP_MAINMENU_PANEL_ABOUT_LABEL5] = cui_Label5;
    lv_obj_add_event_cb(cui_MainMenu, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_MainMenu, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_return_home, ui_event_comp_MainMenu_return_home, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_alarm_setting, ui_event_comp_MainMenu_alarm_setting, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_display_setting, ui_event_comp_MainMenu_display_setting, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_datetime_setting, ui_event_comp_MainMenu_datetime_setting, LV_EVENT_ALL, children);
    ui_comp_MainMenu_create_hook(cui_MainMenu);
    return cui_MainMenu;
}

