#ifndef SYS_CFG_DEFAULTS_H
#define SYS_CFG_DEFAULTS_H

#include "device_config.h"

#ifndef DEVICE_CFG_HW_VER_LEN
#define DEVICE_CFG_HW_VER_LEN 16U
#endif

#ifndef DEVICE_CFG_DEFAULT_SN
#define DEVICE_CFG_DEFAULT_SN "SN9876543210"
#endif
#ifndef DEVICE_CFG_DEFAULT_HW
#define DEVICE_CFG_DEFAULT_HW "HW1314520168"
#endif

#ifndef DEVICE_CFG_DEFAULT_RATE_TH_RH
#define DEVICE_CFG_DEFAULT_RATE_TH_RH  (2.5f)
#endif
#ifndef DEVICE_CFG_DEFAULT_RATE_TH_RL
#define DEVICE_CFG_DEFAULT_RATE_TH_RL  (0.0f)
#endif

#ifndef DEVICE_CFG_DEFAULT_TEMP_TH_HI
#define DEVICE_CFG_DEFAULT_TEMP_TH_HI  (40.0f)
#endif
#ifndef DEVICE_CFG_DEFAULT_TEMP_TH_LO
#define DEVICE_CFG_DEFAULT_TEMP_TH_LO  (0.0f)
#endif

#ifndef DEVICE_CFG_DEFAULT_PRESS_TH_HI
#define DEVICE_CFG_DEFAULT_PRESS_TH_HI  (1080.0f)
#endif
#ifndef DEVICE_CFG_DEFAULT_PRESS_TH_LO
#define DEVICE_CFG_DEFAULT_PRESS_TH_LO  (0.0f)
#endif

#ifndef DEVICE_CFG_DEFAULT_HUM_TH_HI
#define DEVICE_CFG_DEFAULT_HUM_TH_HI  (99.0f)
#endif
#ifndef DEVICE_CFG_DEFAULT_HUM_TH_LO
#define DEVICE_CFG_DEFAULT_HUM_TH_LO  (0.0f)
#endif

#ifndef DEVICE_CFG_DEFAULT_CO2_TH_HI
#define DEVICE_CFG_DEFAULT_CO2_TH_HI  (1200U)
#endif
#ifndef DEVICE_CFG_DEFAULT_CO2_TH_LO
#define DEVICE_CFG_DEFAULT_CO2_TH_LO  (0U)
#endif

#ifndef DEVICE_CFG_DEFAULT_PM25_TH_HI
#define DEVICE_CFG_DEFAULT_PM25_TH_HI  (80U)
#endif
#ifndef DEVICE_CFG_DEFAULT_PM25_TH_LO
#define DEVICE_CFG_DEFAULT_PM25_TH_LO  (0U)
#endif

#ifndef DEVICE_CFG_DEFAULT_ALARM_SOUND
#define DEVICE_CFG_DEFAULT_ALARM_SOUND  (1U)
#endif
#ifndef DEVICE_CFG_DEFAULT_ALARM_LIGHT
#define DEVICE_CFG_DEFAULT_ALARM_LIGHT  (1U)
#endif
#ifndef DEVICE_CFG_DEFAULT_ALARM_VOLUME
#define DEVICE_CFG_DEFAULT_ALARM_VOLUME  (80U)
#endif
#ifndef DEVICE_CFG_DEFAULT_DISPLAY
#define DEVICE_CFG_DEFAULT_DISPLAY  (1U)
#endif
#ifndef DEVICE_CFG_DEFAULT_BRIGHT
#define DEVICE_CFG_DEFAULT_BRIGHT  (100U)
#endif
#ifndef DEVICE_CFG_DEFAULT_LANGUAGE
#define DEVICE_CFG_DEFAULT_LANGUAGE  (0U)
#endif
#ifndef DEVICE_CFG_DEFAULT_SENS
#define DEVICE_CFG_DEFAULT_SENS  (120.0f)
#endif

#define RATE_HIGH_ALARM_BIT  0U
#define RATE_LOW_ALARM_BIT   1U

#endif
